apiVersion: v1
kind: Service
metadata:
  name: dynamo-db
  labels:
    app: nginx-mra
    component: dynamo-db
  namespace: nginx-mra
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    name: tcp
  selector:
    app: nginx-mra
    component: dynamo-db
