apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamo-db-pv-claim
  namespace: nginx-mra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volumeIndex: "pv3"
